name: HPVxHunter
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core languages
  - python=3.8.18
  - perl
  - r-base=4.3

  # Python packages
  - biopython=1.77
  - matplotlib
  - pandas

  # R packages
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readxl
  - r-rcolorbrewer
  - r-stringr

  # Bioinformatics tools
  - vsearch
  - blast
  - muscle
  - meme

  # Perl modules
  - perl-file-find-rule
  - perl-autodie
  - perl-excel-writer-xlsx
